### ISSUE TITLE
SDDT query

### ISSUE THREAD

**Issue by makintos90** [Baio1977/HP-630-CPU-Arrandale-Bios-Legacy-#1]
Hey baio, nice work.
I was wondering which SSDTs you used for this hack? Did you compile all of the SSDTs together?
Also, how did you map all those device properties?
Thanks

**Comment by makintos90** [comment]
I have a very similar HP laptop and am struggling to get opencore working.

**Comment by Baio1977** [comment]
I have merged several SSDTs into one, all of which makes my HP more like a real Mac of SMBios peer.
it is an old laptop, stopped at 10.13 but in the end it works fine, only brightness control does not work, I went crazy but to no avail

**Comment by makintos90** [comment]
Sorry, for asking a newbie question, but from the picture it appears apart from HPET, PNLF and EC, ypu have BUS0, SBUS and others SSDTs. What are those for?
The screenshot is of hackintool right?
Thanks a lot for taking the time to reply.

**Comment by Baio1977** [comment]
https://github.com/5T33Z0/OC-Little-Translated 
You have to study this guide well.
