### ISSUE TITLE
 Possibility to run BigSur

### ISSUE THREAD

**Issue by jtaczanowski** [Baio1977/HP-630-CPU-Arrandale-Bios-Legacy-#2]
Hi,
I managed to get fully working (with graphics acceleration)  BigSur on Arrandale ThinkPad x201. Maybe you will try it on your HP? Repo is [here](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#getting-graphics-qeci-acceleration-to-work)

I think you will only need to install OpenCore Legacy Patched Post install patches described [here](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#getting-graphics-qeci-acceleration-to-work)

Regards

**Comment by Baio1977** [comment]
Seeing your repo I decided to try Big Sur on my HP 630, after updating the kext for 11.4 everything went smoothly, now I have to activate the Wi-Fi, thanks 

![Schermata 2021-08-17 alle 12 00 42](https://user-images.githubusercontent.com/59058746/129707837-23128c44-20a7-47a5-ba0e-82f1cd46fe74.png)
