### ISSUE TITLE
How did you enable iGPU ? I did everything literally everything but still does not work

### ISSUE THREAD

**Issue by Passsword1234** [Baio1977/HP-630-CPU-Arrandale-Bios-Legacy-#4]

**Comment by Baio1977** [comment]
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
                <dict>
                    <key>#AAPL,backlight-control</key>
                    <data>AQAAAA==</data>
                    <key>#applbkl-data</key>
                    <data>AAAAAA==</data>
                    <key>#applbkl-name</key>
                    <data>AQAAAA==</data>
                    <key>device_type</key>
                    <string>VGA compatible controller</string>
                    <key>framebuffer-patch-enable</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-singlelink</key>
                    <data>AQAAAA==</data>
                    <key>model</key>
                    <string>Intel Core Processor Intel Graphics HD</string>
                </dict>

**Comment by Passsword1234** [comment]
do you have discord ?

**Comment by Passsword1234** [comment]
> ```
>             <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
>             <dict>
>                 <key>#AAPL,backlight-control</key>
>                 <data>AQAAAA==</data>
>                 <key>#applbkl-data</key>
>                 <data>AAAAAA==</data>
>                 <key>#applbkl-name</key>
>                 <data>AQAAAA==</data>
>                 <key>device_type</key>
>                 <string>VGA compatible controller</string>
>                 <key>framebuffer-patch-enable</key>
>                 <data>AQAAAA==</data>
>                 <key>framebuffer-singlelink</key>
>                 <data>AQAAAA==</data>
>                 <key>model</key>
>                 <string>Intel Core Processor Intel Graphics HD</string>
>             </dict>
> ```


do you have discord ?

**Comment by Baio1977** [comment]
Telegram Baio1977
